FROM python:3.7
MAINTAINER Marco Cardoso

# Create the user to run the app
RUN adduser --disabled-password --gecos '' app-user

# Install property_anomaly_detector dependencies
RUN mkdir -p /opt/services/property_anomaly_detector

COPY ./packages /opt/services/property_anomaly_detector
WORKDIR /opt/services/property_anomaly_detector/property_anomaly_detector
RUN python setup.py install

# Install the webapp dependencies
WORKDIR /opt/services/property_anomaly_detector/api
RUN pip install -r requirements.txt

# Change run.sh permissions
RUN chmod +x /opt/services/property_anomaly_detector/api/run.sh

RUN chown -R app-user:app-user ./

# Expose port and running cmd as app-user
USER app-user
EXPOSE 5000
CMD ["/bin/sh", "run.sh"]
